# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adaugare.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 557)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(244, 247, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnSend = QtWidgets.QPushButton(self.centralwidget)
        self.btnSend.setGeometry(QtCore.QRect(740, 180, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnSend.setFont(font)
        self.btnSend.setStyleSheet("QPushButton{background-color: rgb(110, 203, 238);\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(19, 184, 245);\n"
"}")
        self.btnSend.setObjectName("btnSend")
        self.btnNewLine = QtWidgets.QPushButton(self.centralwidget)
        self.btnNewLine.setGeometry(QtCore.QRect(740, 60, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnNewLine.setFont(font)
        self.btnNewLine.setStyleSheet("QPushButton{background-color: rgb(110, 203, 238);\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(19, 184, 245);\n"
"}")
        self.btnNewLine.setObjectName("btnNewLine")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 20, 691, 411))
        self.tableWidget.setRowCount(1)
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setObjectName("tableWidget")
        self.btnDelete = QtWidgets.QPushButton(self.centralwidget)
        self.btnDelete.setGeometry(QtCore.QRect(740, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnDelete.setFont(font)
        self.btnDelete.setStyleSheet("QPushButton{background-color: rgb(110, 203, 238);\n"
"border-radius: 0px;\n"
"color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton::hover{\n"
"background-color: rgb(19, 184, 245);\n"
"}")
        self.btnDelete.setObjectName("btnDelete")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnSend.setText(_translate("MainWindow", "Salveaza"))
        self.btnNewLine.setText(_translate("MainWindow", "Insereaza"))
        self.btnDelete.setText(_translate("MainWindow", "Sterge"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
